### ISSUE TITLE
Pythonのプログラムでmanabaから情報を取得する

### ISSUE THREAD

**Issue by yuk1-ishida** [Kento-99/manaba-bot#3]
checkbox付きなので終わったらcheckをつけて行いってください 

わからないことや発見などはコメントで残すこと

- [x] 取得する方法を調べる
- [x] 課題一覧情報を取得する
- [x] 配列などに格納し、値を利用できる状態にする

**Comment by yuk1-ishida** [comment]
そろそろ、「requestライブラリで頑張ってるけど難しいよーん ぴえーん」ってなってるかな？笑

多分だけどmanabaのログインをrequestライブラリでどうにかするのはちょっと難しいかもしれない

webdriverって言って、プログラムからgoogle chromeを自動で動かすPythonのライブラリがあって、それを使うとログイン関連は簡単に突破できるので割とおすすめかも。また今度やってみよ

**Comment by Kento-99** [comment]
seleniumみたいなやつでchrome開いてやる方法は調べれたんですけどいまいちどういじったらいいか分からないんで理解しようとしてるとこです

**Comment by yuk1-ishida** [comment]
にゃーるほど :) 

参考にならんかもだけど、昔に[この動画](https://www.youtube.com/watch?v=f8FXUUQ4uRA&ab_channel=%E3%81%84%E3%81%BE%E3%81%AB%E3%82%85%E3%81%AE%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%9F%E3%83%B3%E3%82%B0%E5%A1%BE)みてちょっと理解できた気がするっす 🫠

**Comment by Kento-99** [comment]
とりあえずIDとパスワードを入力する段階まで書いてみました。まずsign onのページを直接開く形にしたんですが、IDパスワード入力してsign onボタン押すとこまではできるんですが毎回urlが変わるので過去のアクセスみたいになってそこから進めず、今度はmanaba+Rのページからsign onのページに飛んで入力の形にしたんですけどページが開かれるだけで入力されずにタイムアウトします。どうすれば入力してくれるでしょうか

**Comment by yuk1-ishida** [comment]
試してみたらエラーに44行目が通ってないって書いてあるんだけど、`wait.until(EC.title_is('Web Single Sign On | 立命館大学'))`のECってのはどういうものなんですか？
```
Traceback (most recent call last):
  File "/Users/yuki/Apps/line/request.py", line 44, in <module>
    wait.until(EC.title_is('Web Single Sign On | 立命館大学'))
  File "/Users/yuki/.pyenv/versions/3.10.5/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
```

**Comment by Kento-99** [comment]
そのweb上の指定した要素が読み込まれるまで待機するってやつです！

**Comment by yuk1-ishida** [comment]
なるほど。多分なんだけどそのECの効果を受ける対象のHTMLが違う可能性がありそう。だからtitle_isが通らなくてエラーになってると思う。

なんで分かるかというと、途中でprintを入れて確認したら違うtitleが出力されたので

```python
wait = WebDriverWait(driver,10)
# タイトルを出力
print(driver.title) # 結果 : 立命館大学 manaba+Rへようこそ！ |  立命館大学
wait.until(EC.title_is('Web Single Sign On | 立命館大学'))
```

原因としては恐らく以下の部分で遷移が起きてるけど、driverの中に入ってるHTMLは`driver.get('https://www.ritsumei.ac.jp/ct/')`のHTMLが入ってそう。
```python
#manaba+Rボタンをクリック
sign_in_button = driver.find_element(By.ID, 'btnLogin')
sign_in_button.click()
```

**Comment by yuk1-ishida** [comment]
ということで解決策としては最初からログイン画面をgetするようにするか、遷移した後にしっかり新しいHTMLを取得するようにする的な必要があると思う。

後者についてはすぐにはわからんけど、前者に関しては簡単で、ログインのURLは「https://ct.ritsumei.ac.jp/ct/」 を使うと問題なく最初からログイン画面にいけるので途中で遷移するのをやめてこのURLを使うように変更してみるといいかも

**Comment by Kento-99** [comment]
ありがとうございます！やってみます

**Comment by Kento-99** [comment]
一応ログインして未提出課題に飛んで情報を取得してtextで出力までできました！
なんですけど、小テスト、アンケート、レポートの情報を順番に取ってきて出力しようと思ったんですが小テストの情報だけ取って終わっちゃいます

**Comment by yuk1-ishida** [comment]
ちょっとこっちでその状況が再現できないから状況をスクショして見せるか、今試してるコードをpushするかここに貼り付けるかしてほしいっす。

現時点でのpushされたコードを試したら自分のほうでは全部取得できました。

**Comment by Kento-99** [comment]
なんかもっかい試したらできました！ありがとうございます！

**Comment by Kento-99** [comment]
いいやり方かはわかりませんが配列に格納して、期限を読み取って、一日前に迫ってるやつのみ取り出して出力するのできました！

**Comment by yuk1-ishida** [comment]
らじゃ

とりあえずコード動かしてみていろいろ思ったところあるので書きますね。
修正必須項目に関しては直す方が賢明だと思われます。自分の作りたい像に合わせて修正してみてください。

## 修正必須項目

### 1. 使ってないライブラリがインポートされたままになっててちょっと汚い

使ってないライブラリをそのままにしておくのはあまりよろしくないので使ってないのはインポート文を消しておきましょう

### 2. 本当に以内？

課題の期限に関して、以下のコードなんだけど、自分の環境では以内のものが表示されない。
この部分の処理は本当に以内のものも対象になっているのだろうか... 
以内にするならコードを修正する必要があるかも

```python
if deadline - today == datetime.timedelta(days=1): #課題の期限を読み取り、一日以内の場合kadai_arrayに追加する
        kadai_array3.append(report_data)
```

### 3. 配列に何もない時死ぬ

動かして気づいたんだけど、以下のコードだと値が配列にないときにエラーで死にますね
配列に値がない時の処理もほしいかな

```python
# 結果を出力
for data_row1 in kadai_array1:
    minitest_message = f'{data_row1[1]}\n {data_row1[0].strip()}\nの提出期限が迫っています。'
    line_bot_api = LineBotApi(CHANNEL_ACCESS_TOKEN)
    line_bot_api.push_message(USER_ID, TextSendMessage(text=minitest_message))
for data_row2 in kadai_array2:
    questionary_message = f'{data_row2[1]}\n {data_row2[0].strip()}\nの提出期限が迫っています。'
    line_bot_api = LineBotApi(CHANNEL_ACCESS_TOKEN)
    line_bot_api.push_message(USER_ID, TextSendMessage(text=questionary_message))
for data_row3 in kadai_array3:
    report_message = f'{data_row3[1]}\n {data_row3[0].strip()}\nの提出期限が迫っています 。'
    line_bot_api = LineBotApi(CHANNEL_ACCESS_TOKEN)
    line_bot_api.push_message(USER_ID, TextSendMessage(text=report_message))
```

## 4. 画面がいーーーーっぱい

最後にwebdriverを閉じる処理がないのでウィンドが増えて大変。このまま動かすと動く度にウィンドが増えて最終的にメモリを圧迫して爆発してしまうのでwebdriverを使わなくなったらウィンドを閉じるようにコードを追加してほしいっす。


## 努力項目

### forで回す

全体で同じ処理を3回してる部分があるのでfor文で回せるとコードがきれいかも
課題情報を取る時とか
